import React from "react";
import ListStore from "../flux/ListStore";
import ListAction from "../flux/ListAction";
import $ from "jquery";

export default class OpenClass extends React.Component{
    constructor(props){
        super(props);
        this.state={
            classList:ListStore.getClassList()
        }
        this._onChange=this._onChange.bind(this);
        // this._onload=this._onload.bind(this);
    }
    _onChange(){
        this.setState({
            classList:ListStore.getClassList()
        })
    }
   /* _onload(data){
        ListAction.loadData(data)
    }*/
    componentDidMount(){
        var data=[
            {
                "id":"0001",
                "title":"用语言抓住你的学生",
                "imgSrc":"1.jpg",
                "person":8,
                "free":true,
                "price":29.9,
                "learn_person":59,
                "describe":"高中数学知识繁杂而抽象，很多数学老师毫无头绪，资深名师刘淳老师来学科点睛，教学路上助你一臂之力。",
                "introduce":"课程介绍",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"刘纯",
                    "img":"img01.jpg",
                    "introduce":"广州瀚贤教育创始人。新东方20周年功勋教师，新东方集团数学培训师、物理培训师。曾任：新东方集团优能中学培训主管。"
                }
            },
            {
                "id":"0002",
                "title":"英语中表示数字的词根",
                "imgSrc":"2.jpg",
                "person":11,
                "free":true,
                "price":29.9,
                "learn_person":59,
                "describe":"高中数学知识繁杂而抽象，很多数学老师毫无头绪，资深名师刘淳老师来学科点睛，教学路上助你一臂之力。",
                "introduce":"对于英语教学来说，英语词汇的教学一直是一大难题，英语单词多而繁杂，是否有规律技巧可寻？英语词源学家袁新民博士从词根的视角来剖析英语词汇，给英语教师别样的体验和启发。",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"袁新民",
                    "img":"img02.jpg",
                    "introduce":"袁新民，博士，英语词源学家，《不再背单词》系列书作者，德语《屋顶绿化》译者，普特英语特约词汇与词源顾问，专注于从词源与音变的全新角度研究词汇的科学记忆。"
                }
            },
            {
                "id":"0003",
                "title":"面向未来的深度学习",
                "imgSrc":"3.jpg",
                "person":8,
                "free":true,
                "price":19.9,
                "learn_person":59,
                "describe":"你一直在学习，可你会学习吗？面向未来，你该怎样学习，又该怎样教学？“分享大家”晓峰老师带你一起深度学习。",
                "introduce":"你一直在学习，可你会学习吗？面向未来，你该怎样学习，又该怎样教学？“分享大家”晓峰老师，从深度学习的意义到深度学习的方法，带你一起开始深度学习。",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"刘晓峰",
                    "img":"img03.jpg",
                    "introduce":"新东方在线名师，新东方20周年功勋教师。英语口译硕士，人事部二级译员，新东方英语教学专家；新东方教育科技集团教学培训师；新东方考研英语全国巡讲教师；新东方全国北美高峰论坛巡讲教师。曾任：昆明新东方学校国内国外考试部主管、教学教研部主管、教师委员会副主任；成都新东方学校国内考试部、基础英语部、多语种部主任；广州新东方学校英语学习部总监、教师委员会主任；广州新东方学校校长助理。现任北京迪殊科技有限公司副总裁、联合创始人。"
                }
            },
            {
                "id":"0004",
                "title":"高中数学概况",
                "imgSrc":"4.jpg",
                "person":7,
                "free":true,
                "price":19.9,
                "learn_person":59,
                "describe":"高中数学知识繁杂而抽象，很多数学老师毫无头绪，资深名师刘淳老师来学科点睛，教学路上助你一臂之力。",
                "introduce":"高中数学知识繁杂而抽象，很多数学老师毫无头绪，资深名师刘淳老师来学科点睛，从高中数学与初中数学的差异、教学内容和考试内容的差异、数学学科特色及如何解决学生学习中的问题几个方面，抽丝剥茧，教学路上助你一臂之力。",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"刘纯",
                    "img":"img01.jpg",
                    "introduce":"广州瀚贤教育创始人。新东方20周年功勋教师，新东方集团数学培训师、物理培训师。曾任：新东方集团优能中学培训主管。"
                }
            },
            {
                "id":"0005",
                "title":"学术类讲座范例及分析",
                "imgSrc":"5.jpg",
                "person":4,
                "free":true,
                "price":19.9,
                "learn_person":59,
                "describe":"李旭老师逐句示范，拆分讲解，手把手教你做好学术讲座。",
                "introduce":"你有没有过讲课没人听的烦恼？你有没有过讲题讲不明白的困惑？你有没有觉得考研阅读都是长难句？没关系，李旭老师逐句示范，拆分讲解，手把手教你做好学术讲座。",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"李旭",
                    "img":"img05.jpg",
                    "introduce":"讲师简介：李旭，新东方教育科技集团首批“集团演讲师”，美国亚利桑那大学英语系访问学者，口语教学专家。新东方集团十大演讲师冠军，新东方20周年功勋教师，“梦想之旅”讲师团成员，多次与俞敏洪老师同台演讲，人民网教育频道、腾讯网教育频道特邀专家。现任新东方教学培训师以及新东方在线考研阅读、大学英语四六级听力、考研复试口语听力等主讲教师。曾代表新东方优秀培训师赴英国牛津大学、剑桥大学、美国亚利桑那大学访问进修。"
                }
            },
            {
                "id":"0006",
                "title":"二年级的小豆包",
                "imgSrc":"6.jpg",
                "person":4,
                "free":true,
                "price":19.9,
                "learn_person":59,
                "describe":"让王晶老师带我们进入2年级小学生的世界吧！",
                "introduce":" 作为一名新教师，如何站在认知科学的前沿，去认识生命，发现学生的不同，之后，按照生命自身成长的规律去设计教学、引领学生认知自己、发展自己，已经不是一个理念的问题，而是一个实际操作层面的问题。现在，让我们进入2年级小学生的世界吧。",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"王晶",
                    "img":"img06.jpg",
                    "introduce":"清华大学学生职业发展指导中心职业生涯教练，青少年心理专家，“优势教育”理论的创建者。"
                }
            },
            {
                "id":"0007",
                "title":"励志类讲座范例",
                "imgSrc":"7.jpg",
                "person":2,
                "free":true,
                "price":19.9,
                "learn_person":59,
                "describe":"李旭老师带你进入万人演讲的现场，亲自点亮你心里的梦想！",
                "introduce":"2016年新东方学校进行了激动人心的“梦想之旅”全国万人大型演讲，讲师团成员李旭老师以其博学儒雅激动人心的演讲点亮了无数人心里的梦想，如今李旭老师亲自授课，带你进入万人演讲的现场，亲自点亮你心里的梦想！",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"李旭",
                    "img":"img05.jpg",
                    "introduce":"讲师简介：李旭，新东方教育科技集团首批“集团演讲师”，美国亚利桑那大学英语系访问学者，口语教学专家。新东方集团十大演讲师冠军，新东方20周年功勋教师，“梦想之旅”讲师团成员，多次与俞敏洪老师同台演讲，人民网教育频道、腾讯网教育频道特邀专家。现任新东方教学培训师以及新东方在线考研阅读、大学英语四六级听力、考研复试口语听力等主讲教师。曾代表新东方优秀培训师赴英国牛津大学、剑桥大学、美国亚利桑那大学访问进修。"
                }
            },
            {
                "id":"0008",
                "title":"带你一起练书法",
                "imgSrc":"8.jpg",
                "person":3,
                "free":true,
                "price":9.9,
                "learn_person":59,
                "describe":"快来跟着书法名师鲜云老师一起拿起毛笔写起来吧！",
                "introduce":"每天对着电脑、手机，你是不是也快不会写字了？中国书法历史悠久，博大静深，不但有鲜明的艺术性和广泛的实用性，更蕴含了丰富的文化内涵。快来跟着书法名师鲜云老师一起拿起毛笔写起来吧！",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"鲜云",
                    "img":"img08.jpg",
                    "introduce":"号由臼轩、别号枕凡楼主，当代著名青年书法家；北京市书法家协会会员，书法、国学教育工作者；书法教学名师。"
                }
            },
            {
                "id":"0009",
                "title":"如何不输在起跑线上",
                "imgSrc":"9.jpg",
                "person":1,
                "free":true,
                "price":9.9,
                "learn_person":59,
                "describe":"如何不输在起跑线上是困扰中国家长和老师的世纪难题，如今“读书狂”晓峰老师仅用1/3课时就可以告诉你——其实没那么难！",
                "introduce":"课程介绍",
                "courseOnline":[
                    {
                        "chapter":"高中数学概况",
                        "section":[
                            {
                                "tit":"高中数学与初中数学的差异1",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异2",
                                "videoSrc":""
                            },
                            {
                                "tit":"高中数学与初中数学的差异3",
                                "videoSrc":""
                            }
                        ]
                    }
                ],
                "teacher":{
                    "name":"李晓峰",
                    "img":"img03.jpg",
                    "introduce":"新东方在线名师，新东方20周年功勋教师。英语口译硕士，人事部二级译员，新东方英语教学专家；新东方教育科技集团教学培训师；新东方考研英语全国巡讲教师；新东方全国北美高峰论坛巡讲教师。曾任：昆明新东方学校国内国外考试部主管、教学教研部主管、教师委员会副主任；成都新东方学校国内考试部、基础英语部、多语种部主任；广州新东方学校英语学习部总监、教师委员会主任；广州新东方学校校长助理。现任北京迪殊科技有限公司副总裁、联合创始人。"
                }
            }
        ]
        /*var _this=this;
        $.ajax({
            url:"http://172.168.1.177:3030/classDate.json",
            dataType:"json",
            type:"get",
            success:function(data){
                _this._onload(data);
            },
            error:function(err){
                console.log(err);
            }
        });*/
        _onload(data);
        ListStore.addChangeListener(this._onChange);
    }
    componentWillUnmount(){
        // ListStore.removeChangeListener(this._onChange);
    }
    render(){
        return (
            <div>{this.props.children}</div>
        )
    }
}
